development:
  api_key: <%= ENV["last_fm_api_key"] %>
  api_secret: <%= ENV["last_fm_secret"] %>
test:
  api_key: <%= ENV["last_fm_api_key"] %>
  api_secret: <%= ENV["last_fm_secret"] %>
production:
  api_key: <%= ENV["last_fm_api_key"] %>
  api_secret: <%= ENV["last_fm_secret"] %>
